/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lynee
 */
import User.UserStore;
public class LOGIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOGIN.class.getName());

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextfield = new javax.swing.JTextField();
        USERNAMENAME = new javax.swing.JLabel();
        PasswordName = new javax.swing.JLabel();
        USERLOGINNAME = new javax.swing.JLabel();
        USERNAME = new javax.swing.JLabel();
        Passwordname = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        nameREGISTER = new javax.swing.JLabel();
        ResgisterButton = new javax.swing.JButton();
        PasswordTextfield = new javax.swing.JPasswordField();
        ShowPassowrdButton = new javax.swing.JCheckBox();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextfield.addActionListener(this::usernameTextfieldActionPerformed);
        getContentPane().add(usernameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 250, 30));

        USERNAMENAME.setBackground(new java.awt.Color(204, 204, 204));
        USERNAMENAME.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        USERNAMENAME.setForeground(new java.awt.Color(51, 51, 255));
        USERNAMENAME.setText("WARRIOR ID");
        getContentPane().add(USERNAMENAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        PasswordName.setBackground(new java.awt.Color(204, 204, 204));
        PasswordName.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        PasswordName.setForeground(new java.awt.Color(51, 51, 255));
        PasswordName.setText("KAI PASSPHASE");
        getContentPane().add(PasswordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        USERLOGINNAME.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        USERLOGINNAME.setForeground(new java.awt.Color(51, 51, 255));
        USERLOGINNAME.setText("USER LOGIN");
        getContentPane().add(USERLOGINNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 250, -1));

        USERNAME.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        USERNAME.setText("(Username):");
        getContentPane().add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 78, 20));

        Passwordname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Passwordname.setText("(Password):");
        getContentPane().add(Passwordname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        LoginButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 255));
        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(this::LoginButtonActionPerformed);
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 110, -1));

        nameREGISTER.setText("To be come a Supersaiyan?");
        getContentPane().add(nameREGISTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 180, 24));

        ResgisterButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        ResgisterButton.setForeground(new java.awt.Color(51, 51, 255));
        ResgisterButton.setText("Register Here");
        ResgisterButton.addActionListener(this::ResgisterButtonActionPerformed);
        getContentPane().add(ResgisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, 20));
        getContentPane().add(PasswordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 250, 30));

        ShowPassowrdButton.setText("Show Password");
        ShowPassowrdButton.addActionListener(this::ShowPassowrdButtonActionPerformed);
        getContentPane().add(ShowPassowrdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guko vegeta 6.jpg"))); // NOI18N
        Background.setText("jLabel7");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextfieldActionPerformed

    private void ResgisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResgisterButtonActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true); // open register
       this.dispose(); // close login
    }//GEN-LAST:event_ResgisterButtonActionPerformed

    private void ShowPassowrdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassowrdButtonActionPerformed
        // TODO add your handling code here:
        if(ShowPassowrdButton.isSelected()){
            PasswordTextfield.setEchoChar((char)0); // show password
    } else {
           PasswordTextfield.setEchoChar('*'); // hide password
                    
        
       
       
        }
    }//GEN-LAST:event_ShowPassowrdButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
       String username = usernameTextfield.getText().trim();
    String password = new String(PasswordTextfield.getPassword()).trim();

    if(username.isEmpty() || password.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Fill all fields!");
        return;
    }

    // CHECK IF USER REGISTERED
    if(UserStore.savedUsername == null || UserStore.savedPassword == null){
        javax.swing.JOptionPane.showMessageDialog(this, "No registered user found!");
        return;
    }

    // VALIDATE LOGIN
    if(username.equals(UserStore.savedUsername) &&
       password.equals(UserStore.savedPassword)){

        javax.swing.JOptionPane.showMessageDialog(this, "Login Successful!");

        new Dashboard().setVisible(true); // OPEN DASHBOARD
        this.dispose(); // CLOSE LOGIN

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
    }

       
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOGIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PasswordName;
    private javax.swing.JPasswordField PasswordTextfield;
    private javax.swing.JLabel Passwordname;
    private javax.swing.JButton ResgisterButton;
    private javax.swing.JCheckBox ShowPassowrdButton;
    private javax.swing.JLabel USERLOGINNAME;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JLabel USERNAMENAME;
    private javax.swing.JLabel nameREGISTER;
    private javax.swing.JTextField usernameTextfield;
    // End of variables declaration//GEN-END:variables
}
