

public class Register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null); // center window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameName = new javax.swing.JLabel();
        usernameTextfield = new javax.swing.JTextField();
        PasswordName = new javax.swing.JLabel();
        passwordTextfield = new javax.swing.JPasswordField();
        ConfirmPasswordName = new javax.swing.JLabel();
        ConfirmPasswordTextfield = new javax.swing.JPasswordField();
        AlreadyHaveanAccountName = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        ShowPassword = new javax.swing.JCheckBox();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameName.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        UsernameName.setForeground(new java.awt.Color(51, 51, 255));
        UsernameName.setText("Username");
        getContentPane().add(UsernameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 172, -1));

        usernameTextfield.addActionListener(this::usernameTextfieldActionPerformed);
        getContentPane().add(usernameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 270, 39));

        PasswordName.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        PasswordName.setForeground(new java.awt.Color(51, 51, 255));
        PasswordName.setText("Password");
        getContentPane().add(PasswordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 190, 33));
        getContentPane().add(passwordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 270, 37));

        ConfirmPasswordName.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        ConfirmPasswordName.setForeground(new java.awt.Color(51, 51, 255));
        ConfirmPasswordName.setText("Confirm Password");
        getContentPane().add(ConfirmPasswordName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 260, -1));

        ConfirmPasswordTextfield.addActionListener(this::ConfirmPasswordTextfieldActionPerformed);
        getContentPane().add(ConfirmPasswordTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 270, 36));

        AlreadyHaveanAccountName.setText("Already have an Account?");
        getContentPane().add(AlreadyHaveanAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 152, -1));

        RegisterButton.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(51, 51, 255));
        RegisterButton.setText("REGISTER");
        RegisterButton.addActionListener(this::RegisterButtonActionPerformed);
        getContentPane().add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 100, -1));

        LoginButton.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 102, 204));
        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(this::LoginButtonActionPerformed);
        getContentPane().add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(this::ShowPasswordActionPerformed);
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guko vegeta 6.jpg"))); // NOI18N
        BackGround.setText("jLabel5");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextfieldActionPerformed
        // TODO add your handling code here:
        new LOGIN().setVisible(true); // open login
        this.dispose(); // close register
    }//GEN-LAST:event_usernameTextfieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        
        
   String username = usernameTextfield.getText().trim();
    String password = new String(passwordTextfield.getPassword()).trim();
    String confirm = new String(ConfirmPasswordTextfield.getPassword()).trim();

    if(username.isEmpty() || password.isEmpty() || confirm.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Fill all fields!");
        return;
    } 
else if(!password.equals(confirm)){
    javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match!");
} if(!password.equals(confirm)){
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }
String encryptedPassword = CaesarCipher.encrypt(password, 3);
boolean success = AuthFileManager.registerUser(username, encryptedPassword);

    if(success){
        javax.swing.JOptionPane.showMessageDialog(this, "Registered Successfully!");

        new LOGIN().setVisible(true);
        this.dispose();
    } else {
javax.swing.JOptionPane.showMessageDialog(this, "Username already exists!");
    }

    

    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        new LOGIN().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ShowPassword.isSelected()){
        passwordTextfield.setEchoChar((char)0); // show password
        ConfirmPasswordTextfield.setEchoChar((char)0); // show confirm password
    } else {
            passwordTextfield.setEchoChar('*'); // hide password
        ConfirmPasswordTextfield.setEchoChar('*'); // hide confirm password
    
       
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void ConfirmPasswordTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordTextfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConfirmPasswordTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlreadyHaveanAccountName;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel ConfirmPasswordName;
    private javax.swing.JPasswordField ConfirmPasswordTextfield;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel PasswordName;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JLabel UsernameName;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JTextField usernameTextfield;
    // End of variables declaration//GEN-END:variables
}
